
export const RECEIVE_TRACKS = 'RECEIVE_TRACKS';
export const REMOVE_TRACKS = 'REMOVE_TRACKS';

export const UPDATE_RESULTS = 'UPDATE_RESULTS';

export const ADD_TRACKS_TO_PLAYLIST = 'ADD_TRACKS_TO_PLAYLIST';

export const SELECT_TRACK = 'SELECT_TRACK';
export const SET_ON_PAUSE = 'SET_ON_PAUSE';
export const SET_ON_PLAY = 'SET_ON_PLAY';
export const SET_CURRENT_TIME = 'SET_CURRENT_TIME';
export const SET_VOLUME = 'SET_VOLUME';

export const CAPTURE_TIME_SLIDER = 'CAPTURE_TIME_SLIDER';
export const RELEASE_TIME_SLIDER = 'RELEASE_TIME_SLIDER';

export const OPEN_FULL_PLAYER = 'OPEN_FULL_PLAYER';
export const CLOSE_FULL_PLAYER = 'CLOSE_FULL_PLAYER';
